Nama              : (input("Nama                :"))
NIM               : (input("NIM                 :"))
kelasParalel      : (input("Kelas Paralel       :"))
TTL               : (input("Tempat Tanggal Lahir:"))
Alamat            : (input("Alamat              :"))
Hobby             : (input("Hobby               :"))
Nohp              : (input("No. HP              :"))